RegisterNetEvent("redemrp_Deliveryjob:payout")
AddEventHandler("redemrp_Deliveryjob:payout", function(cash, gold, xp)
local _cash = tonumber(cash)
local _gold = tonumber(gold)
local _xp = tonumber(xp)
TriggerEvent('redemrp:getPlayerFromId', source, function(user)
user.addMoney(tonumber(_cash))
user.addGold(tonumber(_gold))
user.addXP(tonumber(_xp))
end)
end)